import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(12, GPIO.IN)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
while 1:
	a=GPIO.input(12)
	print("THE VALUE OF PIN IS= %d" %a)
	time.sleep(1)
	if a==0:
		print("sadi value is 0 switch is ON ")
		GPIO.output(17,1)
		GPIO.output(27,1)
		GPIO.output(22,1)
		time.sleep(.1)		
		GPIO.output(17,0)
		GPIO.output(27,0)
		GPIO.output(22,0)
		time.sleep(.1)
		GPIO.output(17,1)
		GPIO.output(27,1)
		GPIO.output(22,1)
		time.sleep(.1)		
		GPIO.output(17,0)
		GPIO.output(27,0)
		GPIO.output(22,0)								
	else:
		print("sadi value is 1 Switch is OFF ")
		GPIO.output(17,0)
		GPIO.output(27,1)
		GPIO.output(22,1)
		time.sleep(.1)		
		GPIO.output(17,1)
		GPIO.output(27,1)
		GPIO.output(22,0)
		time.sleep(.1)
		GPIO.output(17,0)
		GPIO.output(27,1)
		GPIO.output(22,1)
		time.sleep(.1)		
		GPIO.output(17,1)
		GPIO.output(27,1)
		GPIO.output(22,0)


