import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(5, GPIO.OUT)
GPIO.setup(6, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
while 1:
    print ("all pinms are high")
    GPIO.output(17,1)
    GPIO.output(27,1)
    GPIO.output(22,1)
    GPIO.output(5,1)
    GPIO.output(6,1)
    GPIO.output(13,1)
    GPIO.output(19,1)        
    time.sleep(0.5)
    print ("all pins are low")    
    GPIO.output(17,0)
    GPIO.output(27,0)
    GPIO.output(22,0)
    GPIO.output(5,0)
    GPIO.output(6,0)
    GPIO.output(13,0)
    GPIO.output(19,0)     
    time.sleep(1)
    print ("17,22,6,19 are high and 27 5 13 are low") 
    GPIO.output(17, 1)
    GPIO.output(27,0)
    GPIO.output(22, 1)
    GPIO.output(5,0)
    GPIO.output(6, 1)
    GPIO.output(13,0)
    GPIO.output(19,1) 
    time.sleep(1)
    print ("17,22,6,19 are 0 and 27 5 13 are high")
    GPIO.output(17,0)
    GPIO.output(27, 1)
    GPIO.output(22,0)
    GPIO.output(5, 1)
    GPIO.output(6,0)
    GPIO.output(13,1)
    GPIO.output(19,0)     
    time.sleep(1)
