import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
GPIO.setup(5, GPIO.OUT)
GPIO.setup(6, GPIO.OUT)
GPIO.setup(13, GPIO.OUT)
GPIO.setup(19, GPIO.OUT)
while 1:
    print ("5 high")
    GPIO.output(5,1)
    time.sleep(2)
    GPIO.output(5,0)
    print ("6 high")
    GPIO.output(6,1)
    time.sleep(2)
    GPIO.output(6,0)
    print ("13 high")
    GPIO.output(13,1)
    time.sleep(2)
    GPIO.output(13,0)
    print ("19 high")
    GPIO.output(19,1)
    time.sleep(2)
    GPIO.output(19,0)
    print ("17 high")
    GPIO.output(17,1)
    time.sleep(2)
    GPIO.output(17,0)
    print ("27 high")
    GPIO.output(27,1)
    time.sleep(2)
    GPIO.output(27,0)
    print ("22 high")
    GPIO.output(22,1)
    time.sleep(2)
    GPIO.output(22,0)
