import RPi.GPIO as GPIO
import time
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
while 1:
    GPIO.output(17, 1)
    GPIO.output(27, 0)
    GPIO.output(22, 0)
    time.sleep(0.5)
    GPIO.output(17, 0)
    GPIO.output(27, 1)
    GPIO.output(22, 0)
    time.sleep(0.5)
    GPIO.output(17, 0)
    GPIO.output(27, 0)
    GPIO.output(22, 1)
    time.sleep(0.5)
    GPIO.output(17, 1)
    GPIO.output(27, 1)
    GPIO.output(22, 1)
    time.sleep(0.5)
GPIO.output(17,1)
    GPIO.output(27,1)
    GPIO.output(22,1)  
    GPIO.output(5,1)
    GPIO.output(6,1)
    GPIO.output(13,1)