import RPi.GPIO as GPIO
import time
GPIO.setwarnings(False)
GPIO.setmode(GPIO.BCM)
GPIO.setup(17, GPIO.OUT)
GPIO.setup(27, GPIO.OUT)
GPIO.setup(22, GPIO.OUT)
x = GPIO.PWM(17,50)
y = GPIO.PWM(27,50)
z = GPIO.PWM(22,50)
x.start(10)
y.start(50)
z.start(100)
while 1:
	x.ChangeDutyCycle(5)
	y.ChangeDutyCycle(5)
	z.ChangeDutyCycle(5)		
	time.sleep(1)
	x.ChangeDutyCycle(50)
	y.ChangeDutyCycle(50)
	z.ChangeDutyCycle(50)		
	time.sleep(1)
	x.ChangeDutyCycle(99)
	y.ChangeDutyCycle(99)
	z.ChangeDutyCycle(99)		
	time.sleep(1)	
		
x.stop()
y.stop()
z.stop()
GPIO.cleanup()